In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

### pandas的数据结构

 

#### Series

Series类似于一维数组对象，由一组数据及与之相关的数据标签（索引）。

In [5]:
s1 = Series([2,4,6,8])
s1

0    2
1    4
2    6
3    8
dtype: int64

In [7]:
# 通过values和index属性获取其数组表示形式和索引对象
s1.values

array([2, 4, 6, 8], dtype=int64)

In [8]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
s2 = Series([2,4,6,8],index=list('abcd'))
s2

a    2
b    4
c    6
d    8
dtype: int64

In [10]:
s2['a']

2

In [11]:
s2[['a','c']]

a    2
c    6
dtype: int64

In [12]:
s2[s2>4]

c    6
d    8
dtype: int64

In [13]:
'd' in s2
# 判断某个字符是否是Series对象的索引

True

#### 可以通过字典来创建Series对象

In [15]:
person = {'name':'ldq','age':20,'sex':'m'}
s3 = Series(person)
s3

age      20
name    ldq
sex       m
dtype: object

In [16]:
# 在传入字典时，可以自定义index,如果传入的index不在字典的键中，则会填充NaN值
s4 = Series(person,index=list('abc'))
s4

a   NaN
b   NaN
c   NaN
dtype: float64

#### pandas的isnull和notnull函数可用于检测缺失数据

In [17]:
pd.isnull(s4)

a    True
b    True
c    True
dtype: bool

In [18]:
pd.isnull(s3)

age     False
name    False
sex     False
dtype: bool

#### Series最重要的一个功能是：在算数运算中会 自动对齐不同索引的数据

In [19]:
data1 = {'Ohio':35000,'Oregon':16000,'Texas':71000,'Utah':5000}
data2 = {'California':np.nan,'Ohio':35000,'Oregon':16000,'Texas':71000}

In [20]:
s5 = Series(data1)
s6 = Series(data2)

In [21]:
s5 + s6

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

#### Series对象本身及其索引都有一个name属性

In [22]:
s5.name

In [23]:
s5

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [24]:
s5.name = 'population'

In [25]:
s5

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
Name: population, dtype: int64

In [26]:
# Series的索引可以通过赋值的方式进行修改

### DataFrame

DataFrame是一个表格型的数据结构

In [27]:
# 通过直接传入一个由等长列表或Numpy数组构成的字典
data = {'name':['zhang','shen','liu'],
       'age':[19,18,20],
       'sex':['F','F','M']}
df1 = DataFrame(data)
df1

age   name sex
0   19  zhang   F
1   18   shen   F
2   20    liu   M

In [29]:
df1.sort_index(axis=0)

age   name sex
0   19  zhang   F
1   18   shen   F
2   20    liu   M

In [31]:
# 通过指定columns,实现用户自定义列的排列顺序
df1 = DataFrame(data,columns=['name','sex','age'])
df1

name sex  age
0  zhang   F   19
1   shen   F   18
2    liu   M   20

In [32]:
# 如果传入的列在数据中找不到，会产生NaN值
df2 = DataFrame(data,columns=['name','sex','age','birthday'])
df2

name sex  age birthday
0  zhang   F   19      NaN
1   shen   F   18      NaN
2    liu   M   20      NaN

### 索引列

In [34]:
df2.name

0    zhang
1     shen
2      liu
Name: name, dtype: object

In [35]:
df2['name']

0    zhang
1     shen
2      liu
Name: name, dtype: object

In [37]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [38]:
df2.index=['a','b','c']
df2

name sex  age birthday
a  zhang   F   19      NaN
b   shen   F   18      NaN
c    liu   M   20      NaN

### 行索引

In [39]:
df2.ix['a']

name        zhang
sex             F
age            19
birthday      NaN
Name: a, dtype: object

#### 列可以通过赋值的方式进行修改


In [40]:
df2['birthday'] = '1996-06-18'

In [41]:
df2

name sex  age    birthday
a  zhang   F   19  1996-06-18
b   shen   F   18  1996-06-18
c    liu   M   20  1996-06-18

#### 当列表或数组赋值给某个列时，长度必须和DataFrame的长度相同。如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将填上缺失值

___

#### del 用于删除列

In [42]:
df2.columns

Index(['name', 'sex', 'age', 'birthday'], dtype='object')

In [43]:
df2.columns.values

array(['name', 'sex', 'age', 'birthday'], dtype=object)

In [44]:
del df2['birthday']
df2.columns

Index(['name', 'sex', 'age'], dtype='object')

___

#### 传递嵌套字典构建DataFrame对象

In [45]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [46]:
df3 = DataFrame(pop)

In [47]:
df3
# 外层字典的键作为列，内层字典的键作为行索引

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

___

### 可以向DataFrame构造器传的数据

    二维ndarray   还可传入行标和列标
    由数组、列表组成的字典
    由Series组成的字典
    由字典组成的字典
    另一个DataFrame

___

### 索引对象

In [48]:
obj = Series(range(3),index=['a','b','c'])
obj.index

Index(['a', 'b', 'c'], dtype='object')

#### 所用到的标签都会被转换成一个Index，它具有不可修改性。

___

### Pandas对象的基本功能

#### 重新索引
    reindex()

In [49]:
obj = Series([4.5,7.2,-5.3,3.5],index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.5
dtype: float64

In [50]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.5
d    4.5
e    0.0
dtype: float64

In [51]:
obj

d    4.5
b    7.2
a   -5.3
c    3.5
dtype: float64

___
#### 前向值填充及后向值填充

In [53]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [54]:
obj3.reindex(range(6),method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

___
#### 对于DataFrame,reindex()可以修改行、列索引，如果仅传入一个序列，则会重新索引行

In [55]:
df = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])
df

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [56]:
df2 = df.reindex(['a','b','c','d'])
df2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [57]:
status = ['Texas','Utah','California']
df.reindex(columns=status)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

    reindex()函数的参数
        index
        method           取值可以是ffill(前向值填充) bfill(后向填充值)
        fill_value       重新索引过程中，出现缺失值时要使用的替代值
        copy             默认为True，无论如何都复制；如果为False,则新旧相等不复制
   ___

### 丢弃制定轴上的项
    drop()方法返回的是一个在指定轴上删除了指定值得对象

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
obj = Series(np.arange(5),index=list('abcde'))
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [3]:
new_obj = obj.drop('c')

In [4]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [5]:
obj.drop(['a','c'])

b    1
d    3
e    4
dtype: int32

#### 对于DataFrame，可以删除任意轴上的索引值

In [7]:
data = DataFrame(np.arange(16).reshape((4,4)),
                 index=['Ohio','Colorado','Utah','New York'],
                 columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [10]:
data.drop(['Ohio','New York'])

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [11]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
data.drop(['one','two'],axis=1)

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

___
### 索引、选取、过滤

In [13]:
obj = Series(np.arange(4),index=list('abcd'))
obj

a    0
b    1
c    2
d    3
dtype: int32

In [14]:
obj['a']

0

In [15]:
obj[['a','c']]

a    0
c    2
dtype: int32

In [17]:
obj['a':'c']


a    0
b    1
c    2
dtype: int32

In [18]:
obj[0]

0

In [19]:
obj['a':'c']=5

In [20]:
obj

a    5
b    5
c    5
d    3
dtype: int32

#### 对于DataFrame的索引

In [21]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [22]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [23]:
data.two

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [24]:
data.ix['Ohio']

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [25]:
# 通过bool值进行索引
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [27]:
data.ix['Ohio',['one','two']]

one    0
two    1
Name: Ohio, dtype: int32

In [28]:
data.ix['Ohio':'Utah','one':'three']

one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10

#### DataFrame的索引选项

    obj[val]            选取单个列或一组列
    obj.ix[val]         选取单个行或一组行
    obj.ix[:,val]       选取单个列或列子集
    obj.ix[val1,val2]   限定行、列进行选取
    get_value,set_value 根据行标签和列标签获取单个值
    iloc[行，列]          根据整数位置选取单列或单行，并返回一个Series
  ___

In [29]:
data.get_values()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
data.get_value('Ohio','one')

0

In [35]:
data.iloc[0]

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [36]:
data.iloc[0,0]

0

In [39]:
data.iloc[0,1]

1

### 算数运算与数据对齐
    将对象相加时，如果出现不同的索引，则结果的索引就是该索引的并集。

In [41]:
s1 = Series([7.3,-2.5,3.4,1.5],index=list('acde'))
s2 = Series([-2.1,3.6,-1.5,4,3.1],index=list('acefg'))
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [42]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [46]:
# 对于NaN值进行填充
(s1+s2).fillna(1)

a    5.2
c    1.1
d    1.0
e    0.0
f    1.0
g    1.0
dtype: float64

___
#### 对于DataFrame，对齐操作会同时发生在行和列中

In [48]:
df1 = DataFrame(np.arange(9).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colarado'])
df2 = DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [49]:
df1 + df2

b   c     d   e
Colarado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [52]:
# 在算术方法中填充值
df1.add(df2,fill_value=1)

b    c     d     e
Colarado   7.0  8.0   9.0   NaN
Ohio       3.0  2.0   6.0   6.0
Oregon    10.0  NaN  11.0  12.0
Texas      9.0  5.0  12.0   9.0
Utah       1.0  NaN   2.0   3.0

In [53]:
df1.add(df2)

b   c     d   e
Colarado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [54]:
(df1+df2).fillna(1)

b    c     d    e
Colarado  1.0  1.0   1.0  1.0
Ohio      3.0  1.0   6.0  1.0
Oregon    1.0  1.0   1.0  1.0
Texas     9.0  1.0  12.0  1.0
Utah      1.0  1.0   1.0  1.0

___
### DataFrame和Series之间的运算

In [55]:
arr = np.arange(12).reshape((3,4))

In [58]:
arr[0]

array([0, 1, 2, 3])

In [59]:
# 广播运算
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [62]:
frame = DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
series = frame.ix[0]


In [61]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [63]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [64]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

#### 如果需要匹配行并在列上进行广播，必须使用算术运算方法

In [65]:
series3 = frame['d']
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [67]:
# 按照列进行广播
frame.sub(series3,axis=0)

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

___
### 函数应用和映射

In [71]:
a = lambda x,y:x+y
c = a(5,3)
c    


8

In [72]:
frame = DataFrame(np.random.rand(4,3),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.098630  0.140201  0.922349
Ohio    0.030129  0.778887  0.607355
Texas   0.919886  0.893938  0.718387
Oregon  0.894550  0.863019  0.616196

In [73]:
f = lambda x:x.max()-x.min()
frame.apply(f)

b    0.889757
d    0.753737
e    0.314994
dtype: float64

In [74]:
frame.apply(f,axis=1)

Utah      0.823719
Ohio      0.748758
Texas     0.201499
Oregon    0.278354
dtype: float64

___
### 排序和排名

In [86]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=list('acde'))
obj = pd.Series(np.arange(4),index=['d','a','b','c'])                       

In [87]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [88]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int32

#### 在DataFrame上的应用

In [89]:
frame = DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [90]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [91]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [95]:
# 按值对Series进行排序
obj = pd.Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [96]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [97]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [99]:
# 需要根据一个或多个列中的值进行排序
frame.sort_values(by='a')

a  b
0  0  4
2  0 -3
1  1  7
3  1  2

In [100]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

### 带有重复值的索引

In [101]:
obj = pd.Series(np.arange(5),index=list('aabbc'))
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [102]:
# 索引的is_unique属性可以告诉你它的值是否是唯一的
obj.index.is_unique

False

In [103]:
obj['a']

a    0
a    1
dtype: int32

In [104]:
obj['c']

4

### 汇总和计算描述统计

In [105]:
df = DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],index=list('abcd'),columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [106]:
# 统计出每列的总和
df.sum()

one    9.25
two   -5.80
dtype: float64

In [107]:
df.describe(
)

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [108]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

    描述和统计汇总
        count              非NA值得数量
        median             值得中位数
  ___

### 唯一值、值计数及成员资格

In [109]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [110]:
uniques = obj.unique()

In [111]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [113]:
# 统计各个值出现的次数
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

___
### 缺失值处理

    dropna     

In [114]:
data = pd.Series([1,np.nan,3.5,np.nan,7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [115]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [116]:
data = DataFrame([[1,6.5,3],[1,np.nan,np.nan],[np.nan,np.nan,np.nan],[np.nan,6.5,3]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [117]:
# 丢弃行所有值为NAN的行
cleaned = data.dropna(how = 'all')
cleaned

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [118]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [119]:
# 删除列所有值为NAN的列
data.dropna(how='all',axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [120]:
data.fillna(1)
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [121]:
fill = data.fillna(1)
fill

0    1    2
0  1.0  6.5  3.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
3  1.0  6.5  3.0

In [122]:
# 不同列中的NAN填充不同的值
fill = data.fillna({0:1,1:2,2:3})
fill

0    1    2
0  1.0  6.5  3.0
1  1.0  2.0  3.0
2  1.0  2.0  3.0
3  1.0  6.5  3.0

####  fillna() 默认返回新对象，可以通过指定inplace=True  对现有对象进行修改

___
### 层次化索引

In [124]:
data = pd.Series(np.random.randn(10),index=[list('aaabbbccdd'),list('1231231223')])

In [125]:
data

a  1    0.578760
   2   -0.015712
   3   -1.538989
b  1   -1.180413
   2    1.020287
   3   -0.162160
c  1   -0.356692
   2    0.501999
d  2   -0.898195
   3    1.008594
dtype: float64

In [126]:
data['a']

1    0.578760
2   -0.015712
3   -1.538989
dtype: float64

In [127]:
data.ix[['b','d']]

b  1   -1.180413
   2    1.020287
   3   -0.162160
d  2   -0.898195
   3    1.008594
dtype: float64

In [130]:
data.unstack()

1         2         3
a  0.578760 -0.015712 -1.538989
b -1.180413  1.020287 -0.162160
c -0.356692  0.501999       NaN
d       NaN -0.898195  1.008594