### 合并数据集
    pandas.merge()    根据一个或多个键将不同DataFrame中的行连接起来。
    pandas.concat()   沿着一条轴将多个对象堆叠到一起。

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({'key':list('bbacaab'),'data1':np.arange(7)})
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [3]:
df2 = pd.DataFrame({'key':['a','b','d'],'data2':np.arange(3)})
df2

data2 key
0      0   a
1      1   b
2      2   d

In [7]:

pd.merge(df1,df2)
# 此处没有指定根据哪个列进行连接，此时会将重叠列的列名当作键。
# 根据规定的列，对两个DataFrame中的数据进行合并与展示

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [8]:
df3 =  pd.DataFrame({'key':list('bbacaad'),'data1':np.arange(7)})
pd.merge(df2,df3)

data2 key  data1
0      0   a      2
1      0   a      4
2      0   a      5
3      1   b      0
4      1   b      1
5      2   d      6

___
#### 默认情况下merge()做的是"inner"连接

In [11]:
df3 = pd.DataFrame({'lkey':list('bbacaab'),'data1':np.arange(7)})
df4 = pd.DataFrame({'rkey':['a','b','d'],'data2':np.arange(3)})
pd.merge(df3,df4,left_on='lkey',right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [14]:
# 通过向how= 传递参数，修改连接方式
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [13]:
df1 = pd.DataFrame({'key':list('bbacab'),'data1':np.arange(6)})
df2 = pd.DataFrame({'key':list('ababd'),'data2'})

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [15]:
df1

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b

In [16]:
df2

data2 key
0      0   a
1      1   b
2      2   d

In [17]:
pd.merge(df1,df2,on='key',how='left')

data1 key  data2
0      0   b    1.0
1      1   b    1.0
2      2   a    0.0
3      3   c    NaN
4      4   a    0.0
5      5   a    0.0
6      6   b    1.0

In [18]:
pd.merge(df1,df2,on='key',how='right')

data1 key  data2
0    0.0   b      1
1    1.0   b      1
2    6.0   b      1
3    2.0   a      0
4    4.0   a      0
5    5.0   a      0
6    NaN   d      2

In [19]:
pd.merge(df1,df2,how='inner')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [20]:
pd.merge(df1,df2,how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

####  merge()  的各个参数
    how=         'inner'  'outer'  'left'   'right'  默认为inner
    on=          用于连接的列名。如果未指定，则以列名的交集作为连接键
    left_on      左侧DataFrame中用作连接键的列
    right_on    
    left_index   将左侧的行索引作为其连接键
  ___

### 索引上的合并

In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [3]:
left1 = DataFrame({'key':list('abaabc'),'value':np.arange(6)})

In [4]:
right1 = DataFrame({'group_val':[3.5,7]},index=['a','b'])

In [6]:
pd.merge(left1,right1,left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [7]:
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

    层次化索引数据的合并

In [8]:
lefth = DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],'key2':[2000,2001,2002,2001,2002],'data':np.arange(5)})

In [9]:
righth = DataFrame(np.arange(12).reshape((6,2)),index=[['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],[2001,2000,2000,2000,2001,2002]],columns=['event1','event2'])

In [10]:
lefth

data    key1  key2
0     0    Ohio  2000
1     1    Ohio  2001
2     2    Ohio  2002
3     3  Nevada  2001
4     4  Nevada  2002

In [12]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [13]:
pd.merge(lefth,righth,left_on=['key1','key2'],right_index=True)

data    key1  key2  event1  event2
0     0    Ohio  2000       4       5
0     0    Ohio  2000       6       7
1     1    Ohio  2001       8       9
2     2    Ohio  2002      10      11
3     3  Nevada  2001       0       1

DataFrame 有一个join方法，能够方便地实现按索引合并。还可以用于合并多个带有相同或相似索引的DataFrame对象，而不管他们之间有没有重叠的列。
默认向how= 传递的值是left

In [14]:
left2 = DataFrame([[1,2],[3,4],[5,6]],index=['a','c','e'],columns=["Ohio",'Nevada'])

In [15]:
right2 = DataFrame([[7,8],[9,10],[11,12],[13,14]],index=['b','c','d','e'],columns=['Missouri','Alabama'])

In [16]:
pd.merge(left2,right2,left_index=True,right_index=True)

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [18]:
left2.join(right2,how='inner')

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

___
### 轴向连接

In [19]:
arr = np.arange(12).reshape((3,4))

In [20]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
# 用于合并原始Numpy数组的concatenate函数
np.concatenate([arr,arr],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

####  pandas的concat()

In [23]:
s1 = Series([0,1],index=['a','b'])
s2 = Series([2,3,4],index=['c','d','e'])
s3 = Series([5,6],index=['f','g'])

In [24]:
#合并三个没有重复索引的Series
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [25]:
pd.concat([s1,s2,s3],axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [26]:
pd.concat([s1,s2,s3],axis=1,join='inner')

Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [29]:
# 通过向keys= 传递值，将参与连接的片段在结果中区分开。
pd.concat([s1,s2,s3],keys=['one','two','three'])

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [30]:
pd.concat([s1,s2,s3],keys=['one','two','three'],axis=1)

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

    concat()的各个参数
        join        合并方式   left  right  inner  outer
        keys        用于形成连接轴上的层次化索引

___
### 合并重叠数据

In [31]:
a = Series([np.nan,2.5,np.nan,3.5,4.5,np.nan],index=list('fedcba'))
b = Series(np.arange(len(a),dtype=np.int32),index=a.index)

In [32]:
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [33]:
b

f    0
e    1
d    2
c    3
b    4
a    5
dtype: int32

In [35]:
# 如果a的值为NaN,则取b的值，否则就是a的值
np.where(pd.isnull(a),b,a)

array([ 0. ,  2.5,  2. ,  3.5,  4.5,  5. ])

    对于DataFrame,combine_first()也会对缺失值进行处理
        用参数对象中的数据为调用者对象的缺失数据填充值

In [36]:
df1 = DataFrame({'a':[1,np.nan,5,np.nan],'b':[np.nan,2,np.nan,6],'c':np.arange(2,18,4)})

In [37]:
df2 = DataFrame({'a':[5,4,np.nan,3,7],'b':[np.nan,3,4,6,8]})

In [38]:
df1

a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [39]:
df2

a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [40]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

___
### 重塑和轴向旋转

#### 重塑层次化索引
    stack      将数据的列转为行
    unstack    将数据的行转为列
    

In [41]:
data = DataFrame(np.arange(6).reshape((2,3)),index=pd.Index(['Ohio','Colorado'],names='statu'),columns=pd.Index(['one','two','three'],names='number'))

In [42]:
data

one  two  three
Ohio        0    1      2
Colorado    3    4      5

In [43]:
data.stack()

Ohio      one      0
          two      1
          three    2
Colorado  one      3
          two      4
          three    5
dtype: int32

In [44]:
result = data.stack()

In [45]:
result

Ohio      one      0
          two      1
          three    2
Colorado  one      3
          two      4
          three    5
dtype: int32

In [46]:
# 对于一个层次化索引的Series,可以用unstack将其重排为一个DataFrame,默认情况下操作的是最内层。
result.unstack()

one  two  three
Ohio        0    1      2
Colorado    3    4      5

In [47]:
result.unstack(1)

one  two  three
Ohio        0    1      2
Colorado    3    4      5

In [48]:
result.unstack(0)

Ohio  Colorado
one       0         3
two       1         4
three     2         5

In [49]:
s1 = Series([0,1,2,3],index=['a','b','c','d'])
s2 = Series([4,5,6],index=['c','d','e'])
data2 = pd.concat([s1,s2],keys=['one','two'])

In [50]:
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [53]:
data2.unstack(1)
# 引入了缺失数据

a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [54]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [1]:
import pandas as pd
import numpy as np

### 移除重复数据

In [2]:
data = pd.DataFrame({'k1':['one']*3+['two']*4,'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [3]:
# duplicated()  方法返回一个布尔型Series,表示各行是否是重复行
data.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [4]:
# 移除重复行，返回一个移除了重复行的DataFrame
data.drop_duplicates()


k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [2]:
data = Series([-1,0,-1,1])

In [3]:
data

0   -1
1    0
2   -1
3    1
dtype: int64

In [4]:
data.replace(-1,np.nan)

0    NaN
1    0.0
2    NaN
3    1.0
dtype: float64

In [5]:
data

0   -1
1    0
2   -1
3    1
dtype: int64

In [6]:
# 一次替换多个值
data.replace([-1,0],[2,3])

0    2
1    3
2    2
3    1
dtype: int64